Repository BURG3R5/github-slack-bot, pull requests merged in 2022-08, with the labels that each got.

#55 feat: Show user who starred/unstarred.
  bot/github/github_parsers.py
  bot/slack/messenger.py
Labels: enhancement

#56 fix(slack): Disable unfurling of media links.
  bot/slack/messenger.py
Labels: bug

#60 test: Add demonstrative unittests and file structure.
  bot/github/github_parsers.py
  bot/models/github/event.py
  bot/slack/messenger.py
  main.py
  tests/__init__.py
  tests/github/__init__.py
  tests/github/data.json
  tests/github/test_github_parsers.py
  tests/integration/__init__.py
  tests/slack/__init__.py
  tests/utils/deserializers.py
  tests/utils/load.py
  tests/utils/serializers.py
Labels: tests

#62 chore: add __str__ methods
  bot/models/github/commit.py
  bot/models/github/event.py
  bot/models/slack.py
Labels: tests

#77 fix(test): Fix serializer to properly parse iterators.
  tests/utils/serializers.py
Labels: bug

#79 chore: Do not initialize unnecessary attributes in `GitHubEvent`.
  bot/models/github/event.py
  tests/github/data.json
Labels: enhancement

#78 test: Add unittests for github_parsers.
  bot/github/github_parsers.py
  bot/models/github/event.py
  tests/github/data.json
Labels: tests

#83 refactor(test): Generate parser tests dynamically via metaclass.
  tests/github/test_github_parsers.py
Labels: enhancement, tests
